demo:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  servlet:
    contextPath: /api-demo

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: DEBUG
      com.example.demo: INFO
    pattern:
      console: "%d %-5level %logger : %msg%n"